[relaychain]
default_command = "nh-node"
default_args = [ "-lparachain=debug" ]

chain = "local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true
