name: Cache manager

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at 0:00 UTC
  workflow_dispatch:

jobs:

  clear-caches-job:
    runs-on: ubuntu-latest
    steps:

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Clear caches
        run: |
          sudo apt-get install gh
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          caches_list=$(gh cache list)
          if [ -z "${caches_list}" ]; then
            echo "No caches to delete"
          else
            echo ${caches_list}
            gh cache delete --all
          fi

  build-test-job:
    needs: [clear-caches-job]
    uses: ./.github/workflows/CI-build-test.yml
    with:
      CACHING_MODE: "CACHE_SAVE"

  test-coverage-job:
    needs: [clear-caches-job]
    uses: ./.github/workflows/CI-coverage.yml
    with:
      CACHING_MODE: "CACHE_SAVE"

  lint-format-job:
    needs: [clear-caches-job]
    uses: ./.github/workflows/CI-lint-format.yml
    with:
      CACHING_MODE: "CACHE_SAVE"
    
  e2e-test-job:
    needs: [clear-caches-job]
    uses: ./.github/workflows/CI-e2e-test.yml
    with:
      CACHING_MODE: "CACHE_SAVE"