name: CI-tag-orchestrator

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]*
  workflow_dispatch:

jobs:
  docker-job:
    uses: ./.github/workflows/CI-docker.yml
  rustdoc-job:
    uses: ./.github/workflows/CI-rustdoc.yml